### ISSUE TITLE
Semicolon

### ISSUE THREAD

**Issue by ShalokShalom** [eclipse/ceylon-lang.org#498]
> It's a choice between semicolons or the ugly @annotation syntax for user-defined annotations. You need one or the other, or your language can't be parsed.

What is with whitespace significance?

**Comment by gavinking** [comment]
> whitespace significance?

Significant whitespace doesn't solve the problems with annotations.

**Comment by ShalokShalom** [comment]
Thanks :slightly_smiling_face:

**Comment by ShalokShalom** [comment]
So how is it, that Haskell and others can stay without? :slightly_smiling_face:

**Comment by gavinking** [comment]
Since when does Haskell have annotations?

**Comment by ShalokShalom** [comment]
Oh I see. I thought every language has them, I am a beginner. Thanks for the clearance ^-^

**Comment by gavinking** [comment]
No, not every language has them, and most languages which have them require a syntax like `@foo` whereas Ceylon has a cleaner syntax without the `@`.
