### ISSUE TITLE
SSL certificate broken for wget, curl, etc.

### ISSUE THREAD

**Issue by kingjon3377** [eclipse/ceylon-lang.org#524]
When I (or a CI build of some Ceylon code) try to download something from `https://ceylon-lang.org`, e.g. `https://ceylon-lang.org/download/dist/1_3_3`, I see an error like this:

`ERROR: cannot verify ceylon-lang.org's certificate, issued by ‘CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.`

[This StackExchange answer](https://unix.stackexchange.com/a/559606) leads me to believe this is because the server is only providing the "leaf" SSL certificate, and not any of the intermediate certificates in the chain between the CA's root certificate and the leaf certificate.

(I've only started seeing this error in my CI logs in the last couple of weeks---perhaps the "CA certificate" package on whatever base image Travis uses used to include the necessary intermediate certificate and no longer does?)

**Comment by FroMage** [comment]
Hi,

I should have fixed it, can you confirm?

**Comment by kingjon3377** [comment]
No, the issue is still there, as seen for example in [this CI build I just triggered](https://travis-ci.org/github/kingjon3377/strategicprimer-viewer/builds/753850039).

**Comment by FroMage** [comment]
Actually, I had forgotten to reload the server. Can you try again? This time I verified that the chain is valid.

**Comment by kingjon3377** [comment]
I had wondered. Yes, it now works properly. Thanks!

**Comment by FroMage** [comment]
Excellent, thanks!
